### PR TITLE
User implemented but not logic yet

### PR DESCRIPTION
**Pull request by DavidMarchanDelPino**
Implemented User logic and domain (not commented) but not the logic of the Login

### CODE REVIEW

**Review by ProtossGP32 — COMMENTED** [review]
Please remove the `._,gitignore` and `._.idea` files

Also check tests again

**Comment by ProtossGP32** [comment]
I can't accept this pull request. It is pushing two binary files that shouldn't exit:
`._.gitignore`
`._.idea`

Also, tests must pass before doing a pull request

**Review by ProtossGP32 — CHANGES_REQUESTED** [review]
According to previous comments, please apply the required changes

**Comment by ProtossGP32** [comment]
Please explain why this pull request has been closed. There was already a review and some comments regarding this.

**Comment by DavidMarchanDelPino** [comment]
No se que le pasaba a mi repositorio remoto y lo borré, al hacerlo se cerró. Mañana revisaré e intentaré hacer un pull request que no me ocasione problemas.

**Comment by ProtossGP32** [comment]
Okey, from now on please avoid repeating this procedure as it duplicates work in both creating the pull requests and reviewing them.

Also, from now on, all communications shall be done in English

**Pull request closed without merging**
